Description: "Amazon Forecast Workshop"

Parameters:
  NotebookName:
    Type: String
    Default: AmazonForecastWorkshop
    Description: Enter the name of the SageMaker workshop. Default is SageMakerWorkshop

  DefaultCodeRepo:
    Type: String
    Default: https://github.com/glyfnet/amazon-forecast-samples.git
    Description: Enter the url of a git code repository for this lab
    
  InstanceType:
    Type: String
    Default: ml.t2.medium
    AllowedValues:
      - ml.t2.medium
      - ml.m4.xlarge
      - ml.c5.xlarge
      - ml.p2.xlarge
      - ml.p3.2xlarge
    Description: Enter instance type. Default is ml.t2.medium.

  VolumeSize:
    Type: Number
    Default: 50
    MinValue: 5
    MaxValue: 16384
    ConstraintDescription: Must be an integer between 5 (GB) and 16384 (16 TB).
    Description: Enter the size of the EBS volume in GB. Default is 50 GB.

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join 
                - '-'
                - - 'forecastworkshop'
                  - !Ref 'AWS::AccountId'
      
  AmazonForecastWorkshopRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
        - "arn:aws:iam::aws:policy/AmazonForecastFullAccess"
        - "arn:aws:iam::aws:policy/IAMFullAccess"
              
  SageMakerNotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      InstanceType: !Ref InstanceType
      NotebookInstanceName: !Ref NotebookName
      RoleArn: !GetAtt AmazonForecastWorkshopRole.Arn
      VolumeSizeInGB: !Ref VolumeSize
      DefaultCodeRepository: !Ref DefaultCodeRepo